### ISSUE TITLE
pandas/core/tools/datetime.pyi in pylance more advanced than this repo

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/python-type-stubs#100]
I wanted to do a PR to fix something in `pandas/core/tools/datetime.pyi`, but the version in this repo is way behind what is distributed with pylance.  In this repo, for `to_datetime`, it reads:
```python
def to_datetime(arg, errors: str = ..., dayfirst: bool = ..., yearfirst: bool = ..., utc = ..., format = ..., exact: bool = ..., unit = ..., infer_datetime_format: bool = ..., origin: Union[str, Timestamp] = ..., cache: bool = ...): ...
```
But in pylance v2021.10.0, it has 3 overloads for different types of `arg` .

I can't do a PR without the more up to date version (I need to add another overload).

Why aren't these in sync?

**Comment by jakebailey** [comment]
I've synced the repos; it looks like a slew of fixes from a few months ago (mainly to do with datetime stuff) weren't ported back from our internal repo to the public one. Sorry about that.
