### ISSUE TITLE
Missing attributes in pandas DatetimeIndex 

### ISSUE THREAD

**Issue by mhlg** [microsoft/python-type-stubs#114]
`
from pandas import date_range 
dr = date_range(start='2000-01-01', periods='24', freq='H',  tz='CET')
dayofweek = dr.dayofweek

Cannot access member "dayofweek" for type "DatetimeIndex"
Member "dayofweek" is unknown
`

Other missing attributes:

- year
- month
- day
- hour
- minute
- second
- microsecond
- nanosecond
- date
- time
- timetz
- dayofyear
- day_of_year
- weekofyear
- week
- dayofweek
- day_of_week
- weekday
- quarter

**Comment by gramster** [comment]
Unfortunately pandas uses some voodoo to add those properties to DatetimeIndex; it's not something we can easily infer from the code. So have to close this one as 'can't fix'. If it becomes a real problem we could hack around it via the stubs but that's not really a road we want to go down.
