### ISSUE TITLE
Missing parameters in pandas DatetimeIndex constructor

### ISSUE THREAD

**Issue by mhlg** [microsoft/python-type-stubs#115]
import pandas as pd
pd.DatetimeIndex(data=df[timestamp_column], tz=tz,
                         normalize=False, closed=None,
                         ambiguous='NaT', copy=True)

No parameter named "tz"
No parameter named "normalize"
No parameter named "closed"
No parameter named "ambiguous"

**Comment by Dr-Irv** [comment]
fixed in #160
