### ISSUE TITLE
Correctness of pandas stubs using tests from pandas-stubs

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/python-type-stubs#125]
From discussion at pandas typing meeting on 1/7/2022, and follow up issue here:
https://github.com/pandas-dev/pandas/issues/45253

Using the test snippets from the pandas-stubs project (https://github.com/VirtusLab/pandas-stubs), with the `mypy` settings from the pandas project, there are 119 errors.   See https://github.com/pandas-dev/pandas/issues/45253#issuecomment-1014752287

Should those errors get fixed here as part of this project first?  

Would like advice from @jakebailey and @gramster

**Comment by jakebailey** [comment]
I don't work on Python anymore (officially), so I can't speak for the team, but my guess is that fixing things here would be immediately beneficial for the current users (but someone from our side would have to get them merged and backported).

@judej

**Comment by Dr-Irv** [comment]
@jakebailey I think you've been the one who has been approving my PR's here, so is there now someone else responsible?

**Comment by gramster** [comment]
I'll take a look at how many of these I can address; I will have some time tomorrow.

**Comment by gramster** [comment]
I have added these now with PR https://github.com/microsoft/python-type-stubs/commit/b19436ad3c648d11571089a302b011891d8d67d3; still need to work through a number of them.

**Comment by Dr-Irv** [comment]
So are the CI failures on my latest PRs that I am getting related to the work you need to do to fix them up?

**Comment by Dr-Irv** [comment]
as of #160 tests are integrated and working.  @gramster to confirm
