### ISSUE TITLE
`pandas.io.parsers.TextFileReader` now support `context manager` with `__enter__` and `__exit__` function but not include in stub file

### ISSUE THREAD

**Issue by gramster** [microsoft/python-type-stubs#132]
`pandas.io.parsers.TextFileReader` now support `context manager` with `__enter__` and `__exit__` function but not include in stub file

https://github.com/microsoft/python-type-stubs/blob/e7def7eb38b32fdc1d5b9ae9ad4df25b8696b97e/pandas/io/parsers.pyi#L553-L564

_Originally posted by @yanyongyu in https://github.com/microsoft/python-type-stubs/issues/129#issuecomment-1020775646_

**Comment by Avasam** [comment]
Pandas has been upstreamed and no longer maintained here. https://github.com/pandas-dev/pandas-stubs I think this can be closed.
