### ISSUE TITLE
pandas: Should `Series[Dtype]` be replaced with `Series[S1]` everywhere?

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/python-type-stubs#144]
See comment here in `pyright` 

https://github.com/microsoft/pyright/issues/2985#issuecomment-1030251545

That analysis indicates that the use of `Series[Dtype]` is incorrect, and should possibly be changed to `Series[S1]`.  I'm not brave enough to submit a PR that changes them all, so @gramster should take a look.

**Comment by Dr-Irv** [comment]
@gramster we now only have `Series[Dtype]` in `core/groupby/generic.pyi`  .  You addressed most of these in #156 but should you do it there as well for consistency?

**Comment by gramster** [comment]
We are no longer maintaining the pandas stubs; please open issues at https://github.com/pandas-dev/pandas-stubs
