### ISSUE TITLE
Syntax Errors in pandas.core.{frame,series}

### ISSUE THREAD

**Issue by vst** [microsoft/python-type-stubs#157]
mypy complains about syntax errors here:

1. (Double colon) https://github.com/microsoft/python-type-stubs/blob/509ad0707e5a6fcd1cc43a967a68666e6985ab07/pandas/core/series.pyi#L1391
2. (Indentation) https://github.com/microsoft/python-type-stubs/blob/509ad0707e5a6fcd1cc43a967a68666e6985ab07/pandas/core/frame.pyi#L955

**Comment by Dr-Irv** [comment]
This was fixed in #156

**Comment by vst** [comment]
Alrighty! I guessed so when I saw the big PR, and did not send another PR to avoid conflicts.

Thanks a lot!
