### ISSUE TITLE
request : opencv-contrib

### ISSUE THREAD

**Issue by TheBricktop** [microsoft/python-type-stubs#176]
Is it possible to generate stubs for opencv-contrib ? I've tried to use stubgen but it is not helping at all, the only proper stubs ive found are here but they lack some of the contrib modules (like aruco and rgbd).

**Comment by gramster** [comment]
We don't really have a way to generate stubs; the stubs in this repo are hand-maintained.

**Comment by TheBricktop** [comment]
So the only way now is using the documentation generator or sth like this to create stubs manually or maybe even do a simple script to automate the process.

**Comment by Avasam** [comment]
Given that opencv [can now generates python stubs](https://github.com/opencv/opencv/pull/20370) and opencv-python [has been updated to ship them](https://github.com/opencv/opencv-python/pull/853), you can try the in-development version using `pip install git+https://github.com/opencv/opencv-python.git`. 

You can [set the appropriate environment variables](https://github.com/opencv/opencv-python#ci-build-process) first if you'd like to install a specific package (like headless, contrib or healdless-contrib):
```ini
ENABLE_CONTRIB=1
ENABLE_HEADLESS=1
```

It should work as-is with pyright and mypy, but for Pylance you'll have to remove the bundled stubs every time you update the extension. It can be found at: `%HOMEPATH%\.vscode\extensions\ms-python.vscode-pylance-<VERSION>\dist\bundled\stubs\cv2-stubs` (where `<VERSION>` is your current Pylance version).

If the issue persists, you can raise it upstream.
