### ISSUE TITLE
pylance update procedure/policy

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/python-type-stubs#181]
Maybe for @bschnurr 

#177 was merged in a couple of weeks ago and pylance 2022.3.3 and 2022.3.4 did not include those changes.  

What's the procedure/policy for MS to include the changes here into the pylance releases?  We keep having to hand edit the provided stubs with each release for things that were not merged in...

**Comment by bschnurr** [comment]
@gramster usually handles the merges and he was on vacation. We will have them in for next week, sorry.

**Comment by gramster** [comment]
I am the one who does the merges, and I was away on vacation, so we missed two releases.
