### ISSUE TITLE
VS Code AutoComplete does not include some functions of 3rd Party Modules like (NumPy, Pandas, Matplotlib,...)

### ISSUE THREAD

**Issue by Nobody-loses-like-trump** [microsoft/python-type-stubs#193]
Issue Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

Functions like _df.plot.**area**()_ (The **_area_** part of it)
Or like _df.plot.**bar**()_ (The **_bar_** part of it)
Or attributes like _plt.fill_between(x, y, **color**="skyblue")_ (The **_color_** part of it)

are not recognized as valid so not AutoCompleted

## Steps to reproduce:

1. make an IPython .ipynb (or even a Python .py) file
2. import pandas as pd
3. import matplotlib.pyplot as plt
4. make a df (E.G. df = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6], "C": [7, 8, 9]}))
5. Write the pieces of code I wrote before

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.2
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Default

<details>

<summary>User Settings</summary>

<p>

```

defaultLS: {"defaultLSType":"Pylance"}

downloadLanguageServer: true

envFile: "<placeholder>"

venvPath: "<placeholder>"

venvFolders: "<placeholder>"

condaPath: "<placeholder>"

pipenvPath: "<placeholder>"

poetryPath: "<placeholder>"

languageServer: "Pylance"

linting
• enabled: true
• cwd: "<placeholder>"
• Flake8Args: "<placeholder>"
• flake8Enabled: false
• flake8Path: "<placeholder>"
• lintOnSave: true
• banditArgs: "<placeholder>"
• banditEnabled: false
• banditPath: "<placeholder>"
• mypyArgs: "<placeholder>"
• mypyEnabled: false
• mypyPath: "<placeholder>"
• pycodestyleArgs: "<placeholder>"
• pycodestyleEnabled: false
• pycodestylePath: "<placeholder>"
• prospectorArgs: "<placeholder>"
• prospectorEnabled: false
• prospectorPath: "<placeholder>"
• pydocstyleArgs: "<placeholder>"
• pydocstyleEnabled: false
• pydocstylePath: "<placeholder>"
• pylamaArgs: "<placeholder>"
• pylamaEnabled: false
• pylamaPath: "<placeholder>"
• pylintArgs: "<placeholder>"
• pylintPath: "<placeholder>"

sortImports
• args: "<placeholder>"
• path: "<placeholder>"

formatting
• autopep8Args: "<placeholder>"
• autopep8Path: "<placeholder>"
• provider: "autopep8"
• blackArgs: "<placeholder>"
• blackPath: "<placeholder>"
• yapfArgs: "<placeholder>"
• yapfPath: "<placeholder>"

testing
• cwd: "<placeholder>"
• debugPort: 3000
• nosetestArgs: "<placeholder>"
• nosetestsEnabled: undefined
• nosetestPath: "<placeholder>"
• promptToConfigure: true
• pytestArgs: "<placeholder>"
• pytestEnabled: false
• pytestPath: "<placeholder>"
• unittestArgs: "<placeholder>"
• unittestEnabled: false
• autoTestDiscoverOnSaveEnabled: true

terminal
• activateEnvironment: true
• executeInFileDir: "<placeholder>"
• launchArgs: "<placeholder>"

experiments
• enabled: true
• optInto: []
• optOutFrom: []

insidersChannel: "off"

tensorBoard
• logDirectory: "<placeholder>"

```

</p>
</details>

Extension version: 2022.2.1924087327
VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by gramster** [comment]
We are no longer maintaining the pandas stubs; please open pandas issues at https://github.com/pandas-dev/pandas-stubs

**Comment by gramster** [comment]
We have new matplotlib stubs as of August that should improve things there.

**Comment by Avasam** [comment]
Given that « matplotlib 3.8 will ship with typing stubs » (https://github.com/matplotlib/matplotlib/issues/24701#issuecomment-1530126439), you can try the in-development version using `pip install git+https://github.com/matplotlib/matplotlib.git#egg=matplotlib`.

It should work as-is with pyright and mypy, but for Pylance you'll have to remove the bundled stubs everytime you update the extension. it can be found at: `%HOMEPATH%\.vscode\extensions\ms-python.vscode-pylance-<VERSION>\dist\bundled\stubs\matplotlib` (where `<VERSION>` is your current Pylance version).

**Comment by debonte** [comment]
matplotlib 3.8.0 has shipped and contains their own stubs. We are continuing to ship our stubs for the benefit of users on earlier versions, but we are not planning to make enhancements to them in the future. If our stubs are insufficient for your purposes, you should upgrade to 3.8.0+ and file issues against matplotlib for any improvements that are needed.

> for Pylance you'll have to remove the bundled stubs everytime you update the extension

This is not necessary because matplotlib 3.8.0 is `py.typed` and therefore Pylance will prefer the types provided by the library over our bundled stubs.
