### ISSUE TITLE
`pandas.Index[...]` seems to be resolved as `Hashable` not `Index`

### ISSUE THREAD

**Issue by alkatar21** [microsoft/python-type-stubs#199]
I'm not entirely sure if this is the right repository/place to report this, but I'm guessing it is.

Here an example with pylance/pyright:
```py
# pyright: basic

import pandas as pd

df = pd.DataFrame({'A': [1, 2], 'B': ['c', 'd'], 'E': [3, 4]})

for column in df.columns:  # No typing errors here
    print(column)

print(type(df.columns[df.columns.str.contains('A|B')]))  # No typing errors here
# pandas.core.indexes.base.Index

# "Hashable" is not iterable
#  "__iter__" method not defined Pylance(reportGeneralTypeIssues)
for column in df.columns[df.columns.str.contains('A|B')]:
    print(column)

# Argument of type "Hashable" cannot be assigned to parameter "__obj" of type "Sized" in function "len"
#   "Hashable" is incompatible with protocol "Sized"
#     "__len__" is not present Pylance(reportGeneralTypeIssues)
if len(df.columns[df.columns.str.contains('A|B')]):
    print(True)
```
I am not sure what the reason is. I didn't spot anything here, at least at first glance:
https://github.com/microsoft/python-type-stubs/blob/6b800063bde687cd1846122431e2a729a9de625a/partial/pandas/core/base.pyi#L38

**Comment by Malachov** [comment]
Hello, I have the same experience. I'll add my minimal example
```
import pandas as pd

df = pd.DataFrame([[1, 2, 3]], columns=["a", "b", "c"])

column = df.columns[0]

a = df[column]

print(a)
```
![image](https://user-images.githubusercontent.com/39381691/169521972-6d84b378-a0e5-42d0-9c1b-8adcb9fb1254.png)

Code works OK, but type checker shows error

I'm not sure whether these stubs are used in "user/.vscode/extensions...stubs" though

**Comment by Dr-Irv** [comment]
@alkatar21 @Malachov 

We are in the process of moving the maintenance of these stubs over to https://github.com/pandas-dev/pandas-stubs .  Microsoft has to do some work to copy the stubs there (where I will look at the issues above) over to here.  See #191 .

Can you each report the python version and pandas version you are seeing these errors with?
