### ISSUE TITLE
PyRight doesn't see arguments of constructor for class inherited from pandas.DataFrame

### ISSUE THREAD

**Issue by upginius** [microsoft/python-type-stubs#200]
**Describe the bug**
PyRight doesn't see arguments of constructor for a class that is inherited from pandas.DataFrame.

**To Reproduce**
```python
import pandas as pd


class MyDataFrame(pd.DataFrame):
    def __init__(self, extra_attr: str):
        super().__init__()
        self._extra_attr = extra_attr


test_df = MyDataFrame(extra_attr="test")
```
Got problem: `No parameter named "extra_attr"`

**Expected behavior**
No problems reported.

**VS Code extension or command-line**
Pylance v2022.4.3

**Comment by Avasam** [comment]
Pandas has been upstreamed and no longer maintained here. https://github.com/pandas-dev/pandas-stubs I think this can be closed.
