### ISSUE TITLE
Missing selenium completion

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/python-type-stubs#201]
@karthiknadig thank you for your reply! Yes, I have tried to use the extension pylance, when I input "driver.f" it will prompt "driver.find_element_by_xpath", but when I continue to reference the method ".sent", it still doesn't give any prompt.

_Originally posted by @jill123-cc in https://github.com/microsoft/vscode-python/issues/13333#issuecomment-686985869_

**Comment by Avasam** [comment]
Selenium 4.1.2 released with its own type hints. I think this issue can be closed. (in fact, it could've been ever since moving to typeshed)
