### ISSUE TITLE
vscode autocomplete not working for 'cv2.dnn_DetectionModel' Class

### ISSUE THREAD

**Issue by CCLings** [microsoft/python-type-stubs#202]
```
import cv2
net = cv2.dnn_DetectionModel(weightsPath='', configPath='')
net.setInputSize(320, 320)
```
- conda environment
- opnecv-python:4.5.5.64
- python extension in vscode: v2022.4.0
- pylance extension in vscode: v2022.4.0

**Comment by Avasam** [comment]
Given that opencv [can now generates python stubs](https://github.com/opencv/opencv/pull/20370) and opencv-python [has been updated to ship them](https://github.com/opencv/opencv-python/pull/853), you can try the in-development version using `pip install git+https://github.com/opencv/opencv-python.git`. 

You can [set the appropriate environment variables](https://github.com/opencv/opencv-python#ci-build-process) first if you'd like to install a specific package (like headless, contrib or healdless-contrib):
```ini
ENABLE_CONTRIB=1
ENABLE_HEADLESS=1
```

It should work as-is with pyright and mypy, but for Pylance you'll have to remove the bundled stubs every time you update the extension. It can be found at: `%HOMEPATH%\.vscode\extensions\ms-python.vscode-pylance-<VERSION>\dist\bundled\stubs\cv2-stubs` (where `<VERSION>` is your current Pylance version).

If the issue persists, you can raise it upstream.
