### ISSUE TITLE
Pylance incorrect unreachable result with pwntools

### ISSUE THREAD

**Issue by maple3142** [microsoft/python-type-stubs#203]
Issue Type: <b>Bug</b>

Paste the following code into editor:

```python
from pwn import *

io = process("/bin/cat")


def f():
    io.sendline(b"hello")
    io.sendlineafter(b"hello", b"asd")
    io.interactive()


f()
```

And it you will see the second and third line in function `f` are marked as unreachable for unknown reason.

![image](https://user-images.githubusercontent.com/9370547/134216700-953b19cf-70ca-4075-8d3f-c2e27ef51078.png)
![image](https://user-images.githubusercontent.com/9370547/134216764-a2321299-0649-4b46-bf24-7feebf34ada2.png)

And if you don't wrap those code in a function, this problem wouldn't happen:

![image](https://user-images.githubusercontent.com/9370547/134216893-b29624a4-bd1e-477e-994b-c8a29d669321.png)

Extension version: 2021.9.2
VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.21390
Restricted Mode: No
Remote OS version: Linux x64 5.10.43.3-microsoft-standard-WSL2-maple+

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (6.83GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Arch/home/maple3142/workspace/imaginaryCTF --remote=wsl+Arch|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Arch|
|OS|Linux x64 5.10.43.3-microsoft-standard-WSL2-maple+|
|CPUs|AMD Ryzen 5 3600 6-Core Processor (12 x 3593)|
|Memory (System)|7.77GB (5.53GB free)|
|VM|0%|
</details>

**Comment by Jy447** [comment]
Then how to solve it if I stick to use Pylance

**Comment by erictraut** [comment]
Your options are:
1. Ignore the grayed-out text in this case. It's not hurting anything; primarily aesthetic.
2. File a bug with the maintainers of pwntools and work with them to fix the code in their library.
3. Manually modify the library sources locally on your machine.
4. Write a local partial type stub that provides type information for the module in question.

**Comment by Avasam** [comment]
@Non1187 & @amlamarra
https://github.com/Gallopsled/pwntools/issues/2020#issuecomment-1277249682
> That particular issue is already fixed in dev https://github.com/Gallopsled/pwntools/pull/2069

---

As for the rest of the issue, it's not something Pylance can do anything about, and even if this repo added some stubs, it would eventually end up upstream or in typeshed, so may as well add them there in the first place.
