### ISSUE TITLE
The IntelliSense of Pylance works not well

### ISSUE THREAD

**Issue by gonghenghai** [microsoft/python-type-stubs#210]
-   Language Server version: v2021.11.1
-   OS and version: win10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.5

## Expected behaviour

The IntelliSense of Pylance can work well like the `Jedi` Language Server:

![Screenshot (87)](https://user-images.githubusercontent.com/21306413/141249171-08424e86-7ed8-4627-91e5-54432b845be3.png)

![Capture](https://user-images.githubusercontent.com/21306413/141249512-fa9776b6-02ab-4f56-a4d8-1732b165f6d9.PNG)

## Actual behaviour

![Screenshot (85)](https://user-images.githubusercontent.com/21306413/141249124-8ff84a5c-c6cc-414e-bc6c-e17a7f8294f2.png)

**Comment by gramster** [comment]
This should improve when we update the matplotlib stubs.

**Comment by Trass3r** [comment]
Why aren't they updated more often? The current version seems to be at least 4 months old.

**Comment by gramster** [comment]
> Why aren't they updated more often? The current version seems to be at least 4 months old.

The team is mostly focused on pylance development, not writing type stubs or type annotations, where ideally package authors would take the lead. I am trying to automate this more for some scientific Python packages so that may change a bit in the future. For now, there are new matplotlib stubs as of about mid August.

**Comment by Avasam** [comment]
Given that « matplotlib 3.8 will ship with typing stubs » (https://github.com/matplotlib/matplotlib/issues/24701#issuecomment-1530126439), you can try the in-development version using `pip install git+https://github.com/matplotlib/matplotlib.git#egg=matplotlib`.

It should work as-is with pyright and mypy, but for Pylance you'll have to remove the bundled stubs everytime you update the extension. it can be found at: `%HOMEPATH%\.vscode\extensions\ms-python.vscode-pylance-<VERSION>\dist\bundled\stubs\matplotlib` (where `<VERSION>` is your current Pylance version).

If the issue persists, you can raise it upstream.

**Comment by judej** [comment]
Thanks @Avasam.

 @gonghenghai if this persists after the new version of Matplotlib, please file an issue with the `matplotlib` repoo.
