### ISSUE TITLE
Pylance not be resolved the mongoengine

### ISSUE THREAD

**Issue by daniel-aime** [microsoft/python-type-stubs#212]
Quand je fais importer le module mongoengine, je vois que mon éditeur ne reconnait pas ce module et ça m'a surpris quand même aupparavant mais après quelques jours je me suis rend compte que pylance n'a pas encore pris en charge cette fameux module. Est-ce que je fais cette demande pour qu'il soit là-dedans au futur mise à jour, je pense que ça sera parfait si vous l'intégrez. Cordialement

**Comment by gramster** [comment]
I think we should find out what doesn't work before falling back on wanting a stub.

**Comment by Avasam** [comment]
Works for me
https://pypi.org/project/mongoengine/
![image](https://github.com/microsoft/python-type-stubs/assets/1350584/8f32e7fc-bdeb-4b04-9d5f-7e0f40f23ee4)

**Comment by debonte** [comment]
@daniel-aime, I'm closing this for now. If you are still seeing problems, please post sample code, libraries (and versions) in use, plus the issues/diagnostics that you are seeing.
