### ISSUE TITLE
CV2 stub defines type aliases with circular references

### ISSUE THREAD

**Issue by erictraut** [microsoft/python-type-stubs#213]
The `cv2/__init__.pyi` defines several type aliases that are invalid because they refer to themselves. This leaves them `Unknown`.

Here are a few examples:
```python
VariationalRefinement = _mod_cv2.VariationalRefinement
VideoCapture = _mod_cv2.VideoCapture
VideoWriter = _mod_cv2.VideoWriter
```

Since `_mod_cv2` refers back to this same type stub, these are effectively equivalent to:

```python
VariationalRefinement = VariationalRefinement
VideoCapture = VideoCapture
VideoWriter = VideoWriter
```

Pyright correctly flags these as errors in the stub. They should be fixed.

**Comment by Avasam** [comment]
For anyone else landing here:

Given that opencv [can now generates python stubs](https://github.com/opencv/opencv/pull/20370) and opencv-python [has been updated to ship them](https://github.com/opencv/opencv-python/pull/853), you can try the in-development version using `pip install git+https://github.com/opencv/opencv-python.git`. 

You can [set the appropriate environment variables](https://github.com/opencv/opencv-python#ci-build-process) first if you'd like to install a specific package (like headless, contrib or healdless-contrib):
```ini
ENABLE_CONTRIB=1
ENABLE_HEADLESS=1
```

It should work as-is with pyright and mypy, but for Pylance you'll have to remove the bundled stubs every time you update the extension. It can be found at: `%HOMEPATH%\.vscode\extensions\ms-python.vscode-pylance-<VERSION>\dist\bundled\stubs\cv2-stubs` (where `<VERSION>` is your current Pylance version).

If you have an issue with those generated stubs, you can raise it upstream.
