### ISSUE TITLE
matplotlib markerstyle is incomplete

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/python-type-stubs#214]
Using something like `ax.scatter(s['date'], s['values'], marker = 'o', color = 'red')` gets a complaint 
```
Argument of type "Literal['o']" cannot be assigned to parameter "marker" of type "MarkerStyle | None" in function "scatter"
  Type "Literal['o']" cannot be assigned to type "MarkerStyle | None"
    "Literal['o']" is incompatible with "MarkerStyle"
    Type cannot be assigned to type "None"
```

It looks like some work should be done to update `MarkerStyle` to allow the various literal values documented by matplotlib:
https://matplotlib.org/stable/api/markers_api.html#module-matplotlib.markers

(Note - unlike the work I did with pandas, I won't be contributing to matplotlib type fixes as I rarely use it!)

**Comment by gramster** [comment]
Closing as we pretty much redid the matplotlib stubs from scratch in August.
