### ISSUE TITLE
Gym stubs are out of date

### ISSUE THREAD

**Issue by RedTachyon** [microsoft/python-type-stubs#215]
Hi, I'm a maintainer of [gym](https://github.com/openai/gym), and we just got the following issue: openai/gym#2918 about PyLance type hints in VS Code being wrong.

I don't use PyLance or VS Code, and we don't really use type stubs (instead we just try to put type hints everywhere that we can), so I'm like the last person to try and suggest a solution, but the issue does seem to stem from [this library](https://github.com/microsoft/python-type-stubs/blob/main/gym-stubs/core.pyi#L15)

I'm not sure if this specific annotation is an effect of human error, correctly parsing an old version, or incorrectly parsing any version (I'm pretty sure it wasn't technically correct even in the past, but the code used to be quite messy, so that's understandable), but there are some elements of the type stubs which are definitely simply outdated.

I'm assuming there's an automatic process, so if you could update this somehow, that would be great. This leaves an issue with versioning, since gym is in active development so various elements of the API are changing over time, and type stubs for 0.24.1 won't be fully correct for 0.23.0, not to mention older versions. I'm not sure if you have a solution for that. Or maybe the type hints that we've been adding over the last months are now sufficient and the type stubs can be removed?

**Comment by BlueskyFR** [comment]
@RedTachyon so far, removing the stubs immensely improved typing for Gym in VSCode, so it would just be great to remove them here as I think they don't conver anything anymore
