### ISSUE TITLE
type of subplots is partially unknown in matplotlib plt.subplots

### ISSUE THREAD

**Issue by colinfang** [microsoft/python-type-stubs#216]
with latest pyright (1.1.255)  `typeCheckingMode = "strict"`

```python
import matplotlib.pyplot as plt

_fig, ax = plt.subplots(1, 1)

Type of "subplots" is partially unknown ...
```

The error appeared after this commit   https://github.com/microsoft/python-type-stubs/commit/3e00ef77e0e8727d8512d34a7a489062ea3c5329

**Comment by colinfang** [comment]
nvm, it is caused by numpy array & `reportUnknownMemberType`

https://github.com/microsoft/pyright/issues/1717

**Comment by colinfang** [comment]
A quick workaround would be using `ndarray[Any, Any]` instead of `ndarray`.

**Comment by gramster** [comment]
Closing as we pretty much redid the matplotlib stubs from scratch in August.
