### ISSUE TITLE
Module is not callable

### ISSUE THREAD

**Issue by tiagovla** [microsoft/python-type-stubs#226]
```python
import matplotlib.pyplot as plt
import numpy as np

x, y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
x, y = x.ravel(), y.ravel()
fig, ax = plt.subplots(constrained_layout=True)
ax.tripcolor(x, y, np.sin(x) + np.cos(y))
plt.show()
```
This shows `Module is not callable` at `ax.tripcolor`. This didn't happen before 3ae24b5d69542c83e59bf89266d68de1b3f66c45.

**Comment by judfs** [comment]
I am still seeing this or a similar issue. [Where] Should I make a new issues?

![image](https://github.com/microsoft/python-type-stubs/assets/39133604/5360e749-3013-4536-8a45-5637ea6055e2)

Here both the module and the function are called `acorn`.

```
# my_package/__init__.py
from .acorn import acorn
from .banana import Banana
```

**Comment by debonte** [comment]
@judfs, this repo contains type stubs for popular Python packages such as matplotlib. It sounds like you're having issues with Pylance in conjunction with your own modules? If so, please open an issue at https://github.com/microsoft/pylance-release/issues. Please include a complete, but minimal, set of code files that will reproduce the problem. Or point us to a public repo containing your code.

**Comment by judfs** [comment]
Sorry I meant to leave that comment on this issue https://github.com/microsoft/pylance-release/issues/3313
