### ISSUE TITLE
matplotlib colors.py stub

### ISSUE THREAD

**Issue by omasoud** [microsoft/python-type-stubs#249]
Are these `ListedColormap` constructor signatures supposed to be compatible:

[colors.pyi:82](https://github.com/microsoft/python-type-stubs/blob/3ae24b5d69542c83e59bf89266d68de1b3f66c45/matplotlib/colors.pyi#L82)
```python
    def __init__(self, colors: list, array, name: str = ..., N: int = ...) -> None: ...
```
and [colors.py:1139](https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/colors.py#L1139)
```python
    def __init__(self, colors, name='from_list', N=None):
```
?
There is an extra `array` argument in the former. 
Thanks.

**Comment by gramster** [comment]
The stubs were created by hand; this looks like an error in that the type was probably documented as 'list or array'. Thanks for noticing.

**Comment by Avasam** [comment]
Given that « matplotlib 3.8 will ship with typing stubs » (https://github.com/matplotlib/matplotlib/issues/24701#issuecomment-1530126439), you can try the in-development version using `pip install git+https://github.com/matplotlib/matplotlib.git#egg=matplotlib`.

It should work as-is with pyright and mypy, but for Pylance you'll have to remove the bundled stubs everytime you update the extension. it can be found at: `%HOMEPATH%\.vscode\extensions\ms-python.vscode-pylance-<VERSION>\dist\bundled\stubs\matplotlib` (where `<VERSION>` is your current Pylance version).

If the issue persists, you can raise it upstream.

**Comment by debonte** [comment]
> If a PR is supplied would it be accepted?

@GemmaBoyle, yes, feel free to submit a PR.
