### ISSUE TITLE
Why does the dict returned by matplotlib.pyplot.subplot_mosaic have Text as key type?

### ISSUE THREAD

**Issue by dlukes** [microsoft/python-type-stubs#256]
https://github.com/microsoft/python-type-stubs/blob/259e75cbe35f22c2912166e0ce39bf92bfac00d3/matplotlib/pyplot.pyi#L232

AFAICS, the keys are intended to be regular strings. The following code...

```python
import matplotlib.pyplot as plt
fig, axd = plt.subplot_mosaic("AB;AC")
print(axd["A"])
```

... runs fine...

```console
$ python3 sm.py                                                                                                                                                                                ⚡[1]
AxesSubplot(0.125,0.11;0.352273x0.77)
```

... but fails to typecheck with the following error:

```console
$ pyright sm.py                                                                                                                                                                         ⏰ 00:00:29
Loading configuration file at /Users/david/tmp/sm/pyrightconfig.json
Assuming Python version 3.11
Assuming Python platform Darwin
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
stubPath /Users/david/tmp/sm/typings is not a valid directory.
Searching for source files
Found 1 source file
pyright 1.1.299
/Users/david/tmp/sm/sm.py
  /Users/david/tmp/sm/sm.py:3:7 - error: Argument of type "Literal['A']" cannot be assigned to parameter "__key" of type "Text" in function "__getitem__"
    "Literal['A']" is incompatible with "Text" (reportGeneralTypeIssues)
1 error, 0 warnings, 0 informations
Completed in 0.531sec
```

**Comment by dlukes** [comment]
Oh, same goes for `matplotlib.figure.FigureBase.subplot_mosaic`, of course:

https://github.com/microsoft/python-type-stubs/blob/259e75cbe35f22c2912166e0ce39bf92bfac00d3/matplotlib/figure.pyi#L176

**Comment by Avasam** [comment]
Given that « matplotlib 3.8 will ship with typing stubs » (https://github.com/matplotlib/matplotlib/issues/24701#issuecomment-1530126439), you can try the in-development version using `pip install git+https://github.com/matplotlib/matplotlib.git#egg=matplotlib`.

It should work as-is with pyright and mypy, but for Pylance you'll have to remove the bundled stubs everytime you update the extension. it can be found at: `%HOMEPATH%\.vscode\extensions\ms-python.vscode-pylance-<VERSION>\dist\bundled\stubs\matplotlib` (where `<VERSION>` is your current Pylance version).

If the issue persists, you can raise it upstream.

**Comment by debonte** [comment]
matplotlib 3.8.0 has shipped and contains their own stubs. Pylance is continuing to ship our stubs for the benefit of users on earlier versions, but we are not planning to make enhancements to them in the future. If our stubs are insufficient for your purposes, you should upgrade to 3.8.0+ and file issues against matplotlib for any improvements that are needed.

> for Pylance you'll have to remove the bundled stubs everytime you update the extension

This is not necessary because matplotlib 3.8.0 is `py.typed` and therefore Pylance will prefer the types provided by the library over our bundled stubs.
