### ISSUE TITLE
Error in type stubs of matplotlib for 'widgets.Slider'

### ISSUE THREAD

**Issue by JoeKays** [microsoft/python-type-stubs#268]
Hi everyone,

it seems that the import in line 3 in file [widgets.pyi](https://github.com/microsoft/python-type-stubs/blob/main/matplotlib/widgets.pyi) breaks pylance's type checking when `widgets.Slider` is imported in a project, resulting in the error: `"Slider" is unknown import symbol`

Removing the offending line from widgets.pyi fixes the issue.

Happy coding 😄

**Comment by Avasam** [comment]
Given that « matplotlib 3.8 will ship with typing stubs » (https://github.com/matplotlib/matplotlib/issues/24701#issuecomment-1530126439), you can try the in-development version using `pip install git+https://github.com/matplotlib/matplotlib.git#egg=matplotlib`.

It should work as-is with pyright and mypy, but for Pylance you'll have to remove the bundled stubs everytime you update the extension. it can be found at: `%HOMEPATH%\.vscode\extensions\ms-python.vscode-pylance-<VERSION>\dist\bundled\stubs\matplotlib` (where `<VERSION>` is your current Pylance version).

If the issue persists, you can raise it upstream.
