### ISSUE TITLE
`cv2` missing function `imwritemulti`

### ISSUE THREAD

**Issue by kwsp** [microsoft/python-type-stubs#279]
[`imwritemulti` ](https://docs.opencv.org/4.x/d4/da8/group__imgcodecs.html#ga506e85114c8b4340bb12eca5080205d2)is missing from the type stubs.

However, the corresponding [`imreadmulti`](https://docs.opencv.org/4.x/d4/da8/group__imgcodecs.html#ga4dd47c9ae3d55cc42286cff005825e31) is [present](https://github.com/microsoft/python-type-stubs/blob/03c65909aa1023b9aa6ed7b6c4f2eff26f5bc9b8/cv2/__init__.pyi#LL2539C1-L2540C10).

Looks like this overloaded function was merged into OpenCV 4.5.1:
* Issue: https://github.com/opencv/opencv/pull/18533
* PR: https://github.com/opencv/opencv/pull/18533
* Main tree: https://github.com/opencv/opencv/pull/18951
* Release: https://github.com/opencv/opencv/releases/tag/4.5.1

The current `cv2` type stubs are generated from 4.4.0. When will it be time to update to a newer version? OpenCV stable is at 4.7.0 already.

**Comment by Avasam** [comment]
Given that opencv [can now generates python stubs](https://github.com/opencv/opencv/pull/20370) and opencv-python [has been updated to ship them](https://github.com/opencv/opencv-python/pull/853), you can try the in-development version using `pip install git+https://github.com/opencv/opencv-python.git`. 

You can [set the appropriate environment variables](https://github.com/opencv/opencv-python#ci-build-process) first if you'd like to install a specific package (like headless, contrib or healdless-contrib):
```ini
ENABLE_CONTRIB=1
ENABLE_HEADLESS=1
```

It should work as-is with pyright and mypy, but for Pylance you'll have to remove the bundled stubs every time you update the extension. It can be found at: `%HOMEPATH%\.vscode\extensions\ms-python.vscode-pylance-<VERSION>\dist\bundled\stubs\cv2-stubs` (where `<VERSION>` is your current Pylance version).

If the issue persists, you can raise it upstream.
