### ISSUE TITLE
Run `black` and `isort` automatically or as a hygiene check

### ISSUE THREAD

**Issue by debonte** [microsoft/python-type-stubs#296]
It would be good to match the formatting that typeshed uses. They run `black` and `isort` automatically via a `pre-commit.ci` file. See https://github.com/python/typeshed/blob/main/CONTRIBUTING.md#code-formatting

**Comment by Avasam** [comment]
Whilst it's not a formatter, you may consider Flake8-PYI as well.

Or replace both isort, Flake8 and Flake8-PYI with Ruff for autofixes. Ruff also offers a pre-commit configuration. And is actively working on Black-compatible formatting.
