### ISSUE TITLE
Consider removing the bundled SciPy stubs in favor of the `scipy-stubs` package

### ISSUE THREAD

**Issue by jorenham** [microsoft/python-type-stubs#320]
I'm the author of the novel [`scipy-stubs`](https://github.com/jorenham/scipy-stubs) package, which provides high-quality type stubs for SciPy. It currently passes stubtest, mypy, and Pyright in strict mode.

Given the current quality of the SciPy stubs in this repository, I believe `scipy-stubs` could be a better alternative for SciPy users Since Pylance bundles these stubs (which for SciPy actually increases the number of typing errors), it might be beneficial to consider removing them.

I'd like to open a discussion about potentially adopting `scipy-stubs` or removing the current SciPy stubs from this repository. This change could help improve typing support for SciPy users.

I greatly appreciate the work you've all been doing to enhance typing in Python, and I believe this change could further that goal. I'm open to any feedback or questions you may have about `scipy-stubs`.

Thank you for your consideration.

**Comment by debonte** [comment]
For context, see the discussion at https://github.com/scipy/scipy/issues/21614.

@jorenham, this sounds good to me. Thanks for the time and effort you've invested in this!

I'll remove our stubs.
