### ISSUE TITLE
Missing parameter for sklearn.ensemble.HistGradientBoostingRegressor

### ISSUE THREAD

**Issue by ara-incom** [microsoft/python-type-stubs#322]
Since scikit-learn 1.4 `HistGradientBoostingRegressor` has had parameter `max_features`: https://github.com/scikit-learn/scikit-learn/blob/6e9039160/sklearn/ensemble/_hist_gradient_boosting/gradient_boosting.py#L1499

This appears to be missing from the stubs: https://github.com/microsoft/python-type-stubs/blob/main/stubs/sklearn/ensemble/_hist_gradient_boosting/gradient_boosting.pyi#L90

**Comment by debonte** [comment]
Thanks for the issue. We would welcome a PR with a fix.

**Comment by ara-incom** [comment]
@debonte, I've given it a shot in #323. Let me know if I need to do anything further!

**Comment by debonte** [comment]
@ara-incom, thanks. I won't be able to look at this until Monday. Just wanted to let you know that I saw it and an not ignoring it.
