### ISSUE TITLE
Possible project to pull/merge code from 

### ISSUE THREAD

**Issue by TheCleric** [microsoft/python-type-stubs#36]
https://github.com/predictive-analytics-lab/data-science-types has a lot of stubs for Pandas/NumPy as well. I've contributed there in the past. Not sure how compatible the licensing is, but I would authorize any of my code to be used.

**Comment by jakebailey** [comment]
As far as I know, the licensing on that repo does not permit it to be used in that way. I don't think we're intending for this to be a giant repo of every possible stub, these are just stubs we've worked on (some of which ship with Pylance, which is another thing licensing affects).

Numpy has its own built-in subs, and I believe pandas is partially annotated. It'd be nice to get changes upstreamed (see also #35).

**Comment by gramster** [comment]
I believe those stubs are more limited in scope and focused on type checking; our stubs are more broad, probably more lenient, and are more focused on providing a good editor experience. That said, we do plan to help the pandas team upstream type annotations and will leverage our stubs for that. So if you want to contribute, the *best* place to do is so in the pandas project itself.
